name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci
      
      # --runInBand reduz bastante o tempo dos testes.
      # Sem isso demorou 41s por causa do custo de inicialização. Com isso, demorou 2s.
      - name: Executar testes
        run: npm test -- --runInBand